### PR TITLE
Returning boolean from before() to control if serialization of the object/property should be continued or was done by the before()-method

### PR DESCRIPTION
**Pull request by gadton**
I know that it breaks backward compatibility because of changes of BeanSerializerAdvice but I think it's worth to make advices more flexible. My usecase is to serialize a referenced object based on an annotation as whole object or just as reference, i.e. { "location" : "http://server/app/service/resourceUri" }, so that the client could do lazy-loading.

### CODE REVIEW

**Comment by shyiko** [comment]
Hi. I like the idea but is there any particular reason why not to use `@JsonView` for this kind of thing?

**Comment by gadton** [comment]
Hi, yes for sure ;-)
I want to use it like in the following:

    public class Team {
        private String name;
        private Employee lead;

        @Reference(additionalFields = { "nameWithSalutation", "employeeId" })
        private Set<Employee> member = new HashSet<>();
        ...
    }

`lead` should be render as whole `Employee` object but the list of `member` should be rendered as array of three properties per entry:
- a dynamically calculated value `location` that contains the uri of the service to load the `Employee` with all its values
- the properties `nameWithSalutation`, `employeeId` taken from the `Employee` object, e.g. to be used in a comboBox to choose one member of the team in the UI

Using just views is not sufficient as Jackson only takes one view per property and if I use the `Employee` in several scenarios using sometimes `nameWithSalutation`, sometimes `name` and `givenname` as additional fields I would have to set more than only one view.

Checking for `@Reference` in `before(...)`, serializing the location and the `additionalFields` manually and stopping the serialization for that object whould fit perfectly.

**Comment by shyiko** [comment]
Unless I'm missing something you should be able to specify multiple views per property (see [@JsonView javadoc](http://javadox.com/com.fasterxml.jackson.core/jackson-annotations/2.4.3/com/fasterxml/jackson/annotation/JsonView.html)) + there is [@JsonSerializer](http://fasterxml.github.io/jackson-databind/javadoc/2.3.0/com/fasterxml/jackson/databind/annotation/JsonSerialize.html) which might be a better fit for this particular use case. What do you think?

**Comment by gadton** [comment]
You could define more than one view but I've seen some lines in Jackson code which takes only the first one. Now I had a look at that again an saw that it's only at the endpoint configuration (which is reasonable) => you're right: more than one view per property is possible.

`@JsonSerializer`: that would mean that I have to add `@Reference` to define additional parameters AND `@JsonSerializer`, right? Different things for the same and the developer must not forget one. :-( Additionally the developer has to know the class of the serializer to use all over the project. Ok, that could be solved using some kind of constant but not really nice.
I've also tried it using a `ContextualSerializer` but had no success.

**Comment by shyiko** [comment]
> I have to add `@Reference` to define additional parameters AND `@JsonSerializer`

You could try registering custom serializer as shown [here](https://github.com/FasterXML/jackson-databind/blob/master/src/test/java/com/fasterxml/jackson/databind/contextual/TestContextualSerialization.java#L227). 

Anyway, I think this is worth the addition so I've made the change similar to yours but left `before` signature out. 

1.1.2-SNAPSHOT is already available in
```xml
<repositories>
    <repository>
    <id>sonatype-snapshots</id>
    <url>https://oss.sonatype.org/content/repositories/snapshots</url>
    <snapshots>
        <enabled>true</enabled>
    </snapshots>
    <releases>
        <enabled>false</enabled>
    </releases>
    </repository>
</repositories>
```
for you to try.

Please let me know whether you have any concerns and if not - I'll release 1.2.0.
Thank you.

**Comment by gadton** [comment]
Thanks a lot, for me this is working perfectly!
If you don't mind moving to a newer version of jackson would be great (e.g. 2.4.1 is used in current Wildfly). I think there should be no further code changes necessary.

**Comment by shyiko** [comment]
I've changed com.fasterxml.jackson.core:jackson-databind scope to provided (something that should have been done a long ago, really). This way you won't need to exclude/even dependency on jackson-databind.

Anyway, 1.2.0 should become available through Maven Central in the next 24h.

P.S. Thanks again for the PR. :beer:

**Pull request closed without merging**
